<?php

namespace StageBundle\Repository;

/**
 * TraineeshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraineeshipRepository extends \Doctrine\ORM\EntityRepository
{
}
